Add loading state and error message to Deployment map
NASA-IMPACT/admg-casei pull request #705
Opened 2024-10-31 10:37 UTC by willemarcel

Resolves #703

2024-11-01 16:13 UTC, LanesGood commented on src/components/timeline/timeline-chart.js
> +          <h4>It was not possible to load the map data for this campaign.</h4>
```suggestion
          <h4>There was an issue loading the map data for this campaign</h4>
```

2024-11-01 16:14 UTC, LanesGood requested changes
@willemarcel I think this is looking good, but I'm seeing the error message on every campaign that doesn't have flight data. If I understand the code correctly, this should only appear if there is flight data, but it errors - is that correct? Should there be a `geojson?.features?.length` check combined with the `geojsonError` check?

2024-11-04 05:04 UTC, willemarcel commented
Actually, the only error that can happen is that we don't have a geojson for the campaign. Should we modify the text to state more clearly that it wasn't an error, but the map data for that campaign is not available?

When running locally, you need to enable throttling in your network console to see the loading map component.

2024-11-08 01:23 UTC, LanesGood commented on src/components/timeline/timeline-chart.js
> +          <h4>It was not possible to load the map data for this campaign.</h4>
@willemarcel in the case you've suggested that no errors beyond missing data are present, I would suggest we don't call this an error and use a different icon. 

Lets state "Flight path data is not yet available for this campaign" if that is true.

2024-11-08 18:27 UTC, LanesGood commented
@willemarcel looking again at this, I understand my confusion and think there needs to be some slight refactoring. The `DeploymentMap` is currently a child of the `TimelineChart` component.  In `TimelineChart` the whole component is wrapped in a ReachUI `Disclosure` component to hide or show the timeline. This is behavior is unnecessary to wrap around the Deployment Map.

Instead, I would suggest the following:

- Rename `TimelineSection` to `DeploymentEventsSection`
- Rename `Timeline` directory within "Components" to `DeploymentsEvents`
- Within this new `DeploymentEventsSection`, nest the existing `TimelineChart` and add a new child component, `DeploymentMap`
- Move the existing `MapErrorMsg` and `MapLoading` components to the existing `DeploymentMap` to contain those concerns, and move the geojson fetching/validation logic to that as well

2024-11-08 18:47 UTC, LanesGood commented
New message and icon for empty geojson:
<img width="1165" alt="image" src="https://github.com/user-attachments/assets/25c96010-ed3f-462c-9c55-464e60709637">

Should this be called `MapErrorMsg` or `MapEmptyStateMsg`? Bigger picture, is there a need to call the `error` type of the useFetch hook just for empty data, or could we simply set this message if the `geoJson` response returns `null`, and use a different/more accurate message if there is a true error?

2024-11-14 09:29 UTC, willemarcel commented
> Should this be called `MapErrorMsg` or `MapEmptyStateMsg`?

I like `MapEmptyStateMsg`

> Bigger picture, is there a need to call the `error` type of the useFetch hook just for empty data, or could we simply set this message if the `geoJson` response returns `null`, and use a different/more accurate message if there is a true error?

What we can do instead is check the status code of the request. If it's 404, the geojson file of that campaign was not found.

2024-11-19 16:38 UTC, LanesGood approved these changes

2024-11-19 19:16 UTC, merged